axfapp/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页
    url(r'^market/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
]

axfapp/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns= [


    url(r'^$',views.home,name='home'),
    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^register/$',views.register,name='register'),
    url(r"^login/$",views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout')

]

axfapp/axfapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),


]

axfapp/templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <form action="{% url 'axf:login' %}" method="post">
    {% csrf_token %}
    <p>用户名：<input type="text" placeholder="请输入用户名" name="name"></p>
    <p>密码: <input type="password" placeholder="请输入密码" name="password"></p>
    <p><input type="submit" value="登陆"></p>



    </form>
{% endblock %}

axfapp/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="/static/mine/img/{{ user.img | default:"axf.png" }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <span class="glyphicon glyphicon-user"></span>
                    <a href="{% url 'axf:login' %}">{{ user.name | default:'未登录' }}</a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-th-list"></span>
                    等级: {{ user.rank | default:'无' }}
                </p>
                <a href="{% url 'axf:register' %}" class="register">注册</a>
            </div>
        </div>
        <div class="collect">
            <span class="glyphicon glyphicon-flash"></span>
            <i>商品收藏</i>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#">查看全部订单 <i class="glyphicon glyphicon-chevron-right "></i> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-gift"></span></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-leaf"></span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-random"></span></dt>
                                <dd>优惠劵</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-comment"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-magnet"></span></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-wrench"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            {% if user %}
                <section class="quit">
                    <a href="{% url 'axf:logout' %}">
                        退出
                    </a>
                </section>
            {% endif %}
        </div>
    </div>
{% endblock %}

axfapp/templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    注册
{% endblock %}

{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/registerr.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove "></span>
            </a>
        </div>

        <form action="{% url 'axf:register' %}" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">邮箱</span>
                <input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email">
            </div>

            <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input type="password" class="form-control" placeholder="6~10位数密码" name="password">
            </div>

            <div class="input-group">
                <span class="input-group-addon">确认密码</span>
                <input type="password" class="form-control" placeholder="6~10位数密码">
            </div>

            <div class="input-group">
                <span class="input-group-addon">昵称</span>
                <input type="text" class="form-control" placeholder="昵称" name="name">
            </div>

            <input type="submit" value="注册" id="subButton">
        </form>
    </div>
{% endblock %}