axfapp/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页
    url(r'^market/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
]

axfapp/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns= [


    url(r'^$',views.home,name='home'),
    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^register/$',views.register,name='register'),
    url(r"^login/$",views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout')

]

axfapp/axfapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),


]

axfapp/templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    {#   列表分类#}
    <div class="market">
        <div class="type-slider">
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        <span></span>
                        <a href="{% url 'axf:marketbase' %}">
                            {% if forloop.counter == foodtype.typesort %}
                                {{ foodtype.typename }}

                            {% endif %}
                        </a>
                    </li>
                {% endfor %}


            </ul>
        </div>

        {#    导航#}
        <nav>
            <ul>
                <li id="category-bt">
            <span>全部类型
            <i class="glyphicon glyphicon-chevron-up"></i></span>
                </li>
                <li id="sort-bt">
            <span>综合排序
            <i class="glyphicon glyphicon-chevron-up"></i></span>
                </li>
            </ul>
        </nav>
        {#s商品展示#}
        <div class="main-content">
            {#  全部商品展示 #}
            <div class="content-wrapper">
                <ul>
                    {% for goods in goods_list %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}" alt="" class="goods-img">
                                <div class="goods-info">
                                    <p class="name">{{ goods.productlongname }}</p>
                                    <p class="detailtag">
                                        {% if goods.isxf %}
                                            <span class="xf">精选</span>
                                        {% endif %}
                                        <span>销量：{{ goods.productnum }}</span>
                                    </p>

                                    <p class="specifics">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span class="now-price">{{ goods.price }}</span>
                                        <span class="market-price">{{ goods.marketprice }}</span>
                                    </p>
                                </div>
                            </a>
                            <div class="bt-wrapper">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                                <i>1</i>
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
            <div class="bounce-view ">
                <div class="bounce-wrapper category-view">
                    {% for childtype in childtype_list %}
                        <a href="{% url 'axf:market' childtype.id 0   %}">{{ childtype.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <div class="bounce-view sort-view">
                <div class="bounce-wrapper">
                    <a href="{% url 'axf:market' childid 0 %}">综合排序</a>
                    <a href="{% url 'axf:market' childid 1 %}">销量排序</a>
                    <a href="{% url 'axf:market' childid 2 %}">价格最低</a>
                    <a href="{% url 'axf:market' childid 3 %}">价格最高</a>
                </div>

            </div>
            {#        #}

        </div>


    </div>
{% endblock %}