axfapp/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页
    url(r'^market/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
]

axfapp/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns= [


    url(r'^$',views.home,name='home'),
    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^register/$',views.register,name='register'),
    url(r"^login/$",views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout')

]

axfapp/axfapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),


]

axfapp/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
<link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    {% block extcss %}
    {% endblock %}

</head>
<body>

{% block body %}
    {# 导航#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

    {# 主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

    {# 底部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">首页</div>
                </div>
            </a>
            <a href="{% url 'axf:marketbase' %}" class="market">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">闪购超市</div>
                </div>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">购物车</div>
                </div>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">我的</div>
                </div>
            </a>
        </footer>
    {% endblock %}
{% endblock %}



<script src="{% static 'base/js/jquery.min.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
<script  src="{% static 'base/js/swiper.js' %}"></script>
<script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.js"></script>
{% block extjs %}

{% endblock %}

</body>
</html>